# CLOTHING SIZE RECOMMENDATON SYSTEM.

## Project overview

Online shopping has transformed the fashion industry by allowing customers to purchase clothing from anywhere. However, choosing the correct clothing size remains a major challenge, often resulting in product returns and customer dissatisfaction.

This project aims to develop a machine learning model that recommends the most appropriate clothing size based on an individual's body measurements. The model is expected to support online fashion retailers in providing personalized size recommendations and improving the online shopping experience.

## Business understanding
Selecting the correct clothing size when shopping online is difficult because customers cannot physically try on garments before purchasing. This often leads to incorrect size selection, increased return rates, and lower customer satisfaction.

The stakeholders for this project include:

- **Online Fashion Retailers** – Improve size recommendation systems and reduce product returns.
- **Customers** – Receive personalized clothing size recommendations for better fitting garments.
- **Business Managers** – Improve customer satisfaction while reducing operational costs associated with returns

## Objectives

### Main Objective

Develop a machine learning model that recommends appropriate clothing sizes based on body measurements.

### Specific Objectives
- Explore and understand the anthropometric dataset.
- Perform data cleaning and preprocessing.
- Conduct exploratory data analysis.
- Build and compare multiple classification models.
- Deploy the best-performing model using Streamlit.

# Variables

The ANSUR II dataset contains over 100 anthropometric measurements. For this project, only the variables that are most relevant to clothing size recommendation will be used.

- **Gender** – Participant's sex (Male/Female). This feature will be created when combining the datasets.
- **Stature** – Height of the participant.
- **Weightkg** – Weight of the participant in kilograms.
- **ChestCircumference** – Chest measurement.
- **WaistCircumference** – Waist measurement.
- **HipBreadth** – Hip width measurement.
- **ShoulderBreadth** – Shoulder width measurement.
- **InseamLength** – Measurement from the crotch to the ankle.
- **Clothing Size** – Target variable to be created during feature engineering.

# Dataset Understanding

This project uses the **ANSUR II Anthropometric Dataset**, which contains detailed body measurements collected from male and female participants. The dataset includes over 100 anthropometric measurements such as height, weight, chest circumference, waist circumference, and other body dimensions that are useful for clothing size recommendation.

The dataset is provided in two separate files:
- **ANSUR II MALE Public.csv**
- **ANSUR II FEMALE Public.csv**

These datasets will be merged to create a single dataset for analysis and model development.

**Dataset Source:**
https://www.kaggle.com/datasets/seshadrikolluri/ansur-ii

## Import libraries

In [1]:
# Import Required Libraries
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
# Load the datasets

male = pd.read_csv("ANSUR II MALE Public.csv", encoding="latin1")
female = pd.read_csv("ANSUR II FEMALE Public.csv", encoding="latin1")

In [5]:
# Display the first five rows of each dataset
male.head()

,subjectid,abdominalextensiondepthsitting,acromialheight,acromionradialelength,anklecircumference,axillaheight,balloffootcircumference,balloffootlength,biacromialbreadth,bicepscircumferenceflexed,...,Branch,PrimaryMOS,SubjectsBirthLocation,SubjectNumericRace,Ethnicity,DODRace,Age,Heightin,Weightlbs,WritingPreference
0,10027,266,1467,337,222,1347,253,202,401,369,...,Combat Arms,19D,North Dakota,1,NaN,1,41,71,180,Right hand
1,10032,233,1395,326,220,1293,245,193,394,338,...,Combat Support,68W,New York,1,NaN,1,35,68,160,Left hand
2,10033,287,1430,341,230,1327,256,196,427,408,...,Combat Support,68W,New York,2,NaN,2,42,68,205,Left hand
3,10092,234,1347,310,230,1239,262,199,401,359,...,Combat Service Support,88M,Wisconsin,1,NaN,1,31,66,175,Right hand
4,10093,250,1585,372,247,1478,267,224,435,356,...,Combat Service Support,92G,North Carolina,2,NaN,2,21,77,213,Right hand

In [6]:
female.head()

,SubjectId,abdominalextensiondepthsitting,acromialheight,acromionradialelength,anklecircumference,axillaheight,balloffootcircumference,balloffootlength,biacromialbreadth,bicepscircumferenceflexed,...,Branch,PrimaryMOS,SubjectsBirthLocation,SubjectNumericRace,Ethnicity,DODRace,Age,Heightin,Weightlbs,WritingPreference
0,10037,231,1282,301,204,1180,222,177,373,315,...,Combat Support,92Y,Germany,2,NaN,2,26,61,142,Right hand
1,10038,194,1379,320,207,1292,225,178,372,272,...,Combat Service Support,25U,California,3,Mexican,3,21,64,120,Right hand
2,10042,183,1369,329,233,1271,237,196,397,300,...,Combat Service Support,35D,Texas,1,NaN,1,23,68,147,Right hand
3,10043,261,1356,306,214,1250,240,188,384,364,...,Combat Service Support,25U,District of Columbia,8,Caribbean Islander,2,22,66,175,Right hand
4,10051,309,1303,308,214,1210,217,182,378,320,...,Combat Arms,42A,Texas,1,NaN,1,45,63,195,Right hand

In [7]:
# Check the number of rows and columns
male.shape

(4082, 108)

In [8]:
female.shape

(1986, 108)

In [9]:
# Display dataset information
male.info()
female.info()

<class 'pandas.DataFrame'>
RangeIndex: 4082 entries, 0 to 4081
Columns: 108 entries, subjectid to WritingPreference
dtypes: int64(99), str(9)
memory usage: 3.4 MB
<class 'pandas.DataFrame'>
RangeIndex: 1986 entries, 0 to 1985
Columns: 108 entries, SubjectId to WritingPreference
dtypes: int64(99), str(9)
memory usage: 1.6 MB

In [10]:
# Summary statistics
male.describe()
female.describe()

,SubjectId,abdominalextensiondepthsitting,acromialheight,acromionradialelength,anklecircumference,axillaheight,balloffootcircumference,balloffootlength,biacromialbreadth,bicepscircumferenceflexed,...,waistfrontlengthsitting,waistheightomphalion,weightkg,wristcircumference,wristheight,SubjectNumericRace,DODRace,Age,Heightin,Weightlbs
count,1986.000000,1986.000000,1986.000000,1986.000000,1986.000000,1986.000000,1986.000000,1986.00000,1986.000000,1986.000000,...,1986.000000,1986.000000,1986.000000,1986.000000,1986.000000,1986.000000,1986.000000,1986.000000,1986.000000,1986.000000
mean,22306.606244,229.651057,1335.095166,311.198389,215.739678,1239.029708,228.110272,182.05136,365.348943,305.578550,...,355.136455,980.149043,677.582075,154.792548,794.190332,35.072004,1.781470,28.943605,64.601712,147.505035
std,20904.730297,31.464691,58.079885,17.164691,14.891757,55.801958,11.771007,9.64192,18.298851,30.757033,...,23.945046,50.022715,109.846458,7.827695,38.194755,955.582848,0.999536,8.332078,2.801938,22.855371
min,10037.000000,155.000000,1115.000000,249.000000,170.000000,1038.000000,194.000000,151.00000,283.000000,216.000000,...,289.000000,805.000000,358.000000,124.000000,672.000000,1.000000,1.000000,17.000000,56.000000,86.000000
25%,17667.000000,207.000000,1298.000000,300.000000,205.000000,1202.000000,220.000000,175.00000,353.000000,285.000000,...,338.000000,947.000000,601.000000,150.000000,769.000000,1.000000,1.000000,22.000000,63.000000,130.000000
50%,22096.500000,227.000000,1332.000000,311.000000,215.000000,1236.000000,227.000000,182.00000,365.000000,304.000000,...,355.000000,977.500000,668.000000,154.000000,794.000000,2.000000,2.000000,27.000000,64.000000,145.000000
75%,26089.750000,249.000000,1374.000000,323.000000,225.000000,1277.000000,236.000000,188.00000,378.000000,324.000000,...,370.000000,1013.000000,745.750000,160.000000,819.000000,3.000000,2.000000,34.000000,66.000000,161.000000
max,920103.000000,358.000000,1536.000000,371.000000,275.000000,1419.000000,270.000000,216.00000,422.000000,435.000000,...,432.000000,1142.000000,1196.000000,183.000000,941.000000,42351.000000,6.000000,58.000000,80.000000,270.000000

In [11]:
# Display all column names
male.columns

Index(['subjectid', 'abdominalextensiondepthsitting', 'acromialheight',
       'acromionradialelength', 'anklecircumference', 'axillaheight',
       'balloffootcircumference', 'balloffootlength', 'biacromialbreadth',
       'bicepscircumferenceflexed',
       ...
       'Branch', 'PrimaryMOS', 'SubjectsBirthLocation', 'SubjectNumericRace',
       'Ethnicity', 'DODRace', 'Age', 'Heightin', 'Weightlbs',
       'WritingPreference'],
      dtype='str', length=108)

# Data Cleaning